In [27]:
# 1. Pytorch is known for conveniently expressing Neural Networks
# 2. Pytorch works with Tensor and neural network can be resprsented as a Tensor

In [28]:
import torch
import numpy as np


##1. **TENSORS**

In [29]:
#Tensor is a generalization of Scalar (0d or 0 rank), Vector (1d), Matrix  (2d)

In [30]:
#Building tensor from different objects

In [31]:
#from list data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.dtype)

#from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

#from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data like shape
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

tensor([[1, 2],
        [3, 4]])
torch.int64
tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5824, 0.0044],
        [0.4130, 0.2731]], dtype=torch.float32) 



In [32]:
##Building tensors given shape
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0542, 0.0771, 0.8657],
        [0.1812, 0.8101, 0.9985]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [33]:
#Tensor attributes
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float16
Device tensor is stored on: cpu


In [34]:
##Tensor operations/functions
x = torch.rand(shape)
print("Is tensor",torch.is_tensor([[1,2],[3,4]]))#is_tensor(x)
print("Is non-zero",torch.is_nonzero(torch.tensor([1]))) #only single element is allowed
a = torch.randn(1, 2, 3, 4, 5)#Returns number of elements in the tensor
print("Number of elements", torch.numel(a))

#Acessing and slicing operations
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

#set_default_dtype
torch.set_default_dtype(torch.float16)
torch.tensor([1.2, 3]).dtype

Is tensor False
Is non-zero True
Number of elements 120
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


torch.float16

##**2. VECTOR OPERATIONS**

In [35]:
#DOT PRODUCT
t_one = torch.tensor([1,2,3])
t_two = torch.tensor([1,2,3])
torch.dot(t_one,t_two)

tensor(14)

In [36]:
#from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [37]:
#adjoint of the matrix/tensor
torch.adjoint(x_data)

tensor([[1, 3],
        [2, 4]])

In [38]:
#returns the indices of the tensor where index is non-negative
torch.argwhere(x_data)

tensor([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]])

In [39]:
#concatenate
torch.cat([x_data,x_data],dim=0)

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

## **3. 2 DIMENSIONAL TENSORS**

In [40]:
##VIEW TENSOR
t = torch.arange(16).view(2,2,4)
print("\n",t) ## imagine 2 blocks of 2 rows, 4 columns

t = torch.arange(16).view(4,2,2)
print("\n\n",t) ## imagine 4 blocks of 2 rows, 2 columns


 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])


 tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])


In [41]:
## Slicing 3D tensors
print("\n\n",t[1,:,:])

print("\n\n",t[1,1:2,:])



 tensor([[4, 5],
        [6, 7]])


 tensor([[6, 7]])


In [42]:
## Matrix multiplication
a = torch.arange(6).reshape((3,2))
b = torch.arange(6).reshape((2,3))
print(torch.matmul(a,b))
print(a @ b) ##Both statements are equivalent

tensor([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]])
tensor([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]])


In [49]:
## Horizontal split at the mentioned indices
t = torch.arange(25.0).reshape(5,5)

In [50]:
torch.hsplit(t,[2,4]) ## horizontal split at the mentioned indices

(tensor([[ 0.,  1.],
         [ 5.,  6.],
         [10., 11.],
         [15., 16.],
         [20., 21.]]),
 tensor([[ 2.,  3.],
         [ 7.,  8.],
         [12., 13.],
         [17., 18.],
         [22., 23.]]),
 tensor([[ 4.],
         [ 9.],
         [14.],
         [19.],
         [24.]]))